# gms-data-loader specific environment
# Any dependencies added here should also be added to the combined environment file in python/gms-test-environment.yml
#
# After making any changes to this file, a clean gms-data-loader environment needs to be created, and the lock file regenerated:
# `conda env remove --name gms-data-loader`
# `conda env create --name gms-data-loader --file environment.yml`
# `conda env export --name gms-data-loader --no-builds --channel conda-forge --override-channels | grep -v "prefix" > environment.lock.yml`
#

name: gms-data-loader
channels:
  - conda-forge
dependencies:
  - minio=7.1.14
  - python=3.10.11
  - pyyaml=6.0
  - requests=2.29.0
