spring:
  application:
    name: bridged-data-source-simulator
  processing:
    configuration-names: bridged-data-source-simulator
  codec:
    max-in-memory-size: 10MB

server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/msgpack"
    min-response-size: 1024