{{/* Main template for logging */}}

{{- include "gms.common.configMap.standard" $ }}
{{- include "gms.common.sidecar" $ }}
{{- include "gms.common.secrets.copy" $ }}
{{- include "gms.common.configMaps.copy" $ }}

{{- range $index, $appName := .Values.standardApps }}
{{- $appContext := mustMergeOverwrite (mustDeepCopy $) (dict "appValues" (get $.Values $appName)) (dict "appName" $appName) }}
{{- include "gms.common.app.standard" $appContext }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gms
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
automountServiceAccountToken: false
{{- if semverCompare "<1.25-0" (include "gms.common.capabilities.kubeVersion" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  gms
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
rules:
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
    - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gms
  labels:
    {{- include "gms.common.labels.standard" . | trim | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gms
subjects:
- kind: ServiceAccount
  name: gms
{{- end }}