---- MAIN WAVEFORM DDL

CREATE SCHEMA IF NOT EXISTS GMS_GLOBAL AUTHORIZATION GMS_GLOBAL;
CREATE TABLE IF NOT EXISTS GMS_GLOBAL.QCMASKINFO
(
    QCMASKID NUMBER(18), 
	  STA VARCHAR2(6), 
	  CHAN VARCHAR2(8), 
	  TIME FLOAT(53), 
	  ENDTIME FLOAT(53), 
	  SAMPRATE FLOAT(24), 
	  NSEG NUMBER(8), 
	  QCDEFID NUMBER(18), 
	  AUTH VARCHAR2(15), 
	  LDDATE DATE 
);

CREATE TABLE IF NOT EXISTS GMS_GLOBAL.QCMASKSEG 
(	
    QCMASKID NUMBER(18), 
    STARTSAMPLE NUMBER(8), 
    ENDSAMPLE NUMBER(8), 
    MASKTYPE NUMBER(5), 
    AUTH VARCHAR2(15), 
    LDDATE DATE
);

