#ifndef TEST_FILTER_TYPE_H
#define TEST_FILTER_TYPE_H

enum TEST_FILTER_TYPE
{
    BW_LP_CAUSAL_FILTER = 0,
    BW_LP_CAUSAL_DESIGNED_FILTER,
    BW_HP_NONCAUSAL_FILTER,
    BW_HP_NONCAUSAL_DESIGNED_FILTER,
    BW_HP_CAUSAL_FILTER,
    BW_HP_CAUSAL_DESIGNED_FILTER,
    BW_BP_CAUSAL_FILTER,
    BW_BP_CAUSAL_DESIGNED_FILTER,
    BW_BR_NONCAUSAL_FILTER,
    BW_BR_NONCAUSAL_DESIGNED_FILTER,
    CASCADED_FILTER_LPHP_FILTER,
    CASCADED_FILTER_LPHP_DESIGNED_FILTER,
    TAPER_FWD,
    TAPER_REV,
    TAPER_BOTH

};

#endif // TEST_FILTER_TYPE_H