spring:
  application:
    name: signal-detection
  processing:
    configuration-names: signal-detection
  codec:
    max-in-memory-size: 20MB

server:
  compression:
    enabled: true
    mime-types: "text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/msgpack"
    min-response-size: 1024
  servlet:
    context-path: /signal-detection-manager-service

gms:
  persistence:
    account: gms_global_ro
    unit: gms_station_definition

signalDetectionPersistenceUnitName: gms_signal_detection

qcMaskPersistenceUnitName: gms_qc_mask
qcMaskDurationTimeConfig: qc-mask.qc-duration-time-parameters
qcMaskJdbcUrlConfig: qc-mask.jdbc_url

monitoringOrgConfig: global.monitoring-org
accountsByStageConfig: global.stage-accounts
orderedStagesConfig: workflow-manager.workflow-definition
waveformLeadLagConfig: signal-detection.waveform-lead-lag

signalEnhancementConfiguration:
  hostname: signal-enhancement-configuration-service
  contextPath: /signal-enhancement-configuration
  port: 8080
  urlPaths:
    filterDefsByUsageForSDHs: /default-filter-definitions-for-signal-detection-hypotheses
    

springdoc:
  swagger-ui:
    disable-swagger-default-url: true