# config-loader specific environment
# Any dependencies added here should also be added to the combined environment file in python/gms-test-environment.yml
#
# After making any changes to this file, a clean config-loader environment needs to be created, and the lock file regenerated:
# `conda env remove --name config-loader`
# `conda env create --name config-loader --file environment.yml`
# `conda env export --name config-loader --no-builds --channel conda-forge --override-channels | grep -v "prefix" > environment.lock.yml`
#

name: config-loader
channels:
  - conda-forge
dependencies:
  - flask-executor=1.0.0
  - flask-sqlalchemy=3.0.3
  - flask=2.3.2
  - gunicorn=20.1.0
  - python=3.10.11
  - pyyaml=6.0
  - requests=2.29.0
