enableTelemetry: false

nmHoistingLimits: none

packageExtensions:
  "@blueprintjs/core@*":
    dependencies:
      react-dom: 18.1.0
  "@blueprintjs/eslint-plugin@*":
    dependencies:
      tslib: 2.4.0
  "@cfaester/enzyme-adapter-react-18@*":
    dependencies:
      function.prototype.name: 1.1.5
      has: 1.0.3
      prop-types: 15.8.1
  "@testing-library/user-event@*":
    dependencies:
      "@testing-library/dom": 8.5.0
  debug@*:
    dependencies:
      supports-color: 8.1.1
  follow-redirects@*:
    dependencies:
      debug: 4.3.4
  jest-config@*:
    dependencies:
      ts-node: 9.1.1
      typescript: 5.1.6
  react-popper@*:
    dependencies:
      react-dom: 18.1.0
  redux-electron-store@*:
    dependencies:
      electron: 19.0.8
  redux-mock-store@*:
    dependencies:
      redux: 4.1.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: "@yarnpkg/plugin-exec"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

supportedArchitectures:
  cpu:
    - current
    - x86
    - x64
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.6.1.cjs
